<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Medoo\\' => array($vendorDir . '/catfan/medoo/src'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Config\\' => array($baseDir . '/config'),
    'Common\\' => array($baseDir . '/app/common'),
    'Business\\' => array($baseDir . '/app/business'),
    'Admin\\' => array($baseDir . '/app/admin'),
);
